In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset = pd.read_csv("Covid Dataset.csv")

In [3]:
dataset.head()

Breathing Problem  Fever  Dry Cough  Sore throat  Running 0se  Asthma  \
0                  1      1          1            1            1       0   
1                  1      1          1            1            0       1   
2                  1      1          1            1            1       1   
3                  1      1          1            0            0       1   
4                  1      1          1            1            1       0   

   Chronic Lung Disease  Headache  Heart Disease  Diabetes  ...  Fatigue   \
0                     0         0              0         1  ...         1   
1                     1         1              0         0  ...         1   
2                     1         1              0         1  ...         1   
3                     0         0              1         1  ...         0   
4                     1         1              1         1  ...         0   

   Gastrointestinal   Abroad travel  Contact with COVID Patient  \
0                  1              0                           1   
1                  0              0                           0   
2                  1              1                           0   
3                  0              1                           0   
4                  1              0                           1   

   Attended Large Gathering  Visited Public Exposed Places  \
0                         0                              1   
1                         1                              1   
2                         0                              0   
3                         1                              1   
4                         0                              1   

   Family working in Public Exposed Places  Wearing Masks  \
0                                        1              0   
1                                        0              0   
2                                        0              0   
3                                        0              0   
4                                        0              0   

   Sanitization from Market  COVID-19  
0                         0         1  
1                         0         1  
2                         0         1  
3                         0         1  
4                         0         1  

[5 rows x 21 columns]

In [4]:
X = dataset.iloc[:,0:20]
Y = dataset.iloc[:,20]

In [5]:
X.head()

Breathing Problem  Fever  Dry Cough  Sore throat  Running 0se  Asthma  \
0                  1      1          1            1            1       0   
1                  1      1          1            1            0       1   
2                  1      1          1            1            1       1   
3                  1      1          1            0            0       1   
4                  1      1          1            1            1       0   

   Chronic Lung Disease  Headache  Heart Disease  Diabetes  Hyper Tension  \
0                     0         0              0         1              1   
1                     1         1              0         0              0   
2                     1         1              0         1              0   
3                     0         0              1         1              0   
4                     1         1              1         1              1   

   Fatigue   Gastrointestinal   Abroad travel  Contact with COVID Patient  \
0         1                  1              0                           1   
1         1                  0              0                           0   
2         1                  1              1                           0   
3         0                  0              1                           0   
4         0                  1              0                           1   

   Attended Large Gathering  Visited Public Exposed Places  \
0                         0                              1   
1                         1                              1   
2                         0                              0   
3                         1                              1   
4                         0                              1   

   Family working in Public Exposed Places  Wearing Masks  \
0                                        1              0   
1                                        0              0   
2                                        0              0   
3                                        0              0   
4                                        0              0   

   Sanitization from Market  
0                         0  
1                         0  
2                         0  
3                         0  
4                         0

In [6]:
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: COVID-19, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=.2,random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler

stc = StandardScaler()
X_train = stc.fit_transform(X_train)
X_test = stc.transform(X_test)

In [9]:
X_train

array([[-1.39826055,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       [ 0.71517429,  0.52419468,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ],
       [ 0.71517429, -1.9076882 ,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ],
       ...,
       [ 0.71517429,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       [-1.39826055,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       [ 0.71517429, -1.9076882 ,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ]])

In [10]:
X_test

array([[ 0.71517429,  0.52419468,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ],
       [ 0.71517429,  0.52419468,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ],
       [-1.39826055,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       ...,
       [ 0.71517429,  0.52419468,  0.51812776, ...,  1.19406082,
         0.        ,  0.        ],
       [-1.39826055, -1.9076882 , -1.93002591, ...,  1.19406082,
         0.        ,  0.        ],
       [ 0.71517429,  0.52419468,  0.51812776, ..., -0.83747828,
         0.        ,  0.        ]])

In [11]:
X.shape

(5434, 20)

In [12]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import ReLU
from keras.layers import Dropout

In [13]:
classifier = Sequential()

classifier.add(Dense(20 , input_dim = 20 ,activation='relu'))
classifier.add(Dense(40 , activation='relu'))
classifier.add(Dense(20 , activation='relu'))
classifier.add(Dense(10 , activation='relu'))
classifier.add(Dense(5 ,  activation='relu'))

classifier.add(Dense(1 , activation='sigmoid'))

classifier.compile(loss = 'binary_crossentropy' ,optimizer = 'adam' , metrics = ['accuracy'])

In [14]:
model_history = classifier.fit(X_train,Y_train,validation_split=0.33,batch_size=10,epochs=100)

Epoch 1/100
292/292 [==============================] - 1s 4ms/step - loss: 0.2786 - accuracy: 0.8874 - val_loss: 0.1029 - val_accuracy: 0.9617
Epoch 2/100
292/292 [==============================] - 1s 4ms/step - loss: 0.0959 - accuracy: 0.9633 - val_loss: 0.0558 - val_accuracy: 0.9770
Epoch 3/100
292/292 [==============================] - 1s 4ms/step - loss: 0.0566 - accuracy: 0.9742 - val_loss: 0.0521 - val_accuracy: 0.9791
Epoch 4/100
292/292 [==============================] - 1s 4ms/step - loss: 0.0482 - accuracy: 0.9784 - val_loss: 0.0423 - val_accuracy: 0.9777
Epoch 5/100
292/292 [==============================] - 1s 4ms/step - loss: 0.0449 - accuracy: 0.9777 - val_loss: 0.0367 - val_accuracy: 0.9784
Epoch 6/100
292/292 [==============================] - 1s 4ms/step - loss: 0.0407 - accuracy: 0.9808 - val_loss: 0.0346 - val_accuracy: 0.9812
Epoch 7/100
292/292 [==============================] - 1s 4ms/step - loss: 0.0410 - accuracy: 0.9787 - val_loss: 0.0371 - val_accuracy: 0.9805

Epoch 58/100
292/292 [==============================] - 1s 4ms/step - loss: 0.0333 - accuracy: 0.9828 - val_loss: 0.0306 - val_accuracy: 0.9833
Epoch 59/100
292/292 [==============================] - 1s 4ms/step - loss: 0.0332 - accuracy: 0.9828 - val_loss: 0.0302 - val_accuracy: 0.9833
Epoch 60/100
292/292 [==============================] - 1s 3ms/step - loss: 0.0332 - accuracy: 0.9828 - val_loss: 0.0303 - val_accuracy: 0.9833
Epoch 61/100
292/292 [==============================] - 1s 4ms/step - loss: 0.0335 - accuracy: 0.9825 - val_loss: 0.0311 - val_accuracy: 0.9833
Epoch 62/100
292/292 [==============================] - 1s 4ms/step - loss: 0.0377 - accuracy: 0.9811 - val_loss: 0.0301 - val_accuracy: 0.9833
Epoch 63/100
292/292 [==============================] - 1s 3ms/step - loss: 0.0331 - accuracy: 0.9828 - val_loss: 0.0307 - val_accuracy: 0.9833
Epoch 64/100
292/292 [==============================] - 1s 3ms/step - loss: 0.0332 - accuracy: 0.9821 - val_loss: 0.0307 - val_accuracy:

In [15]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [16]:
# # Making the Confusion Matrix
# from sklearn.metrics import confusion_matrix
# cm = confusion_matrix(Y_test, y_pred)
# print(cm)
# # Calculate the Accuracy
# from sklearn.metrics import accuracy_score
# score=accuracy_score(y_pred,Y_test)
# print(score*100)

In [17]:
X.head()

Breathing Problem  Fever  Dry Cough  Sore throat  Running 0se  Asthma  \
0                  1      1          1            1            1       0   
1                  1      1          1            1            0       1   
2                  1      1          1            1            1       1   
3                  1      1          1            0            0       1   
4                  1      1          1            1            1       0   

   Chronic Lung Disease  Headache  Heart Disease  Diabetes  Hyper Tension  \
0                     0         0              0         1              1   
1                     1         1              0         0              0   
2                     1         1              0         1              0   
3                     0         0              1         1              0   
4                     1         1              1         1              1   

   Fatigue   Gastrointestinal   Abroad travel  Contact with COVID Patient  \
0         1                  1              0                           1   
1         1                  0              0                           0   
2         1                  1              1                           0   
3         0                  0              1                           0   
4         0                  1              0                           1   

   Attended Large Gathering  Visited Public Exposed Places  \
0                         0                              1   
1                         1                              1   
2                         0                              0   
3                         1                              1   
4                         0                              1   

   Family working in Public Exposed Places  Wearing Masks  \
0                                        1              0   
1                                        0              0   
2                                        0              0   
3                                        0              0   
4                                        0              0   

   Sanitization from Market  
0                         0  
1                         0  
2                         0  
3                         0  
4                         0

In [19]:
classifier.predict([[1,0,0,1,1,1,0,1,0,1,1,1,0,1,1,1,0,1,0,0]])

array([[1.]], dtype=float32)